### ISSUE TITLE
map undefined

### ISSUE THREAD

**Issue by timhowgego** [planarnetwork/transxchange2gtfs#11]
This fatal error is triggered by [NE_310_PB3954_19.xml](https://github.com/planarnetwork/transxchange2gtfs/files/3055673/Fatal_NE_310_PB3954_19.zip) within the current Traveline North East dataset. It prevents parsing any archive containing it, without reporting the filename causing the failure. Running today's code.

(node:12012) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at TransXChangeStream.getJourneySections ( ... TransXChangeStream.js:50:64)
    at Array.reduce (<anonymous>)
    at TransXChangeStream._transform ( ... TransXChangeStream.js:29:81)
    at TransXChangeStream.Transform._read (_stream_transform.js:190:10)
    at TransXChangeStream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at TransXChangeStream.Writable.write (_stream_writable.js:294:11)
    at XMLStream.ondata (_stream_readable.js:666:20)
    at XMLStream.emit (events.js:182:13)
(node:12012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12012) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by linusnorton** [comment]
JPS_O87 has an empty JourneyPatternSection - any ideas what that means?

**Comment by linusnorton** [comment]
This has been fixed in version 1.2.3 - for now anything with an empty set of timing links is ignored.
