### ISSUE TITLE
Sections of undefined

### ISSUE THREAD

**Issue by timhowgego** [planarnetwork/transxchange2gtfs#12]
Fatal error with Traveline North West's current [NW_04_SCMN_7_2_A.xml](https://github.com/planarnetwork/transxchange2gtfs/files/3057667/Fatal_NW_04_SCMN_7_2_A.zip) (Stagecoach Manchester 7 Ashton-Stockport). Not fixed by 1.2.3, although the error suggests a similar referencing problem.

(Regarding #11, I can only assume an entirely empty JourneyPatternSection was added erroneously. The schema says the JourneyPatternSection "declares and groups an ordered collection of JourneyPatternTimingLink elements", implying it is invalid if empty. So such parsing just needs to fail gracefully, as in 1.2.3.)

(node:4660) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Sections' of undefined
    at TransXChangeJourneyStream._transform ( ... TransXChangeJourneyStream.js:32:45)
    at TransXChangeJourneyStream.Transform._read (_stream_transform.js:190:10)
    at TransXChangeJourneyStream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at TransXChangeJourneyStream.Writable.write (_stream_writable.js:294:11)
    at TransXChangeStream.ondata (_stream_readable.js:666:20)
    at TransXChangeStream.emit (events.js:187:15)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
(node:4660) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4660) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by linusnorton** [comment]
@timhowgego I'm not sure how but this has slipped through the cracks. Can you confirm whether this is still an issue?

**Comment by timhowgego** [comment]
Still an issue for 1.3.1 with the attached sample xml file. However the current Traveline North West dataset does now parse successfully, so the bug may reflect mis-formed data or an edge case.

**Comment by linusnorton** [comment]
Okay, I will close this for now but please re-open if it occurs again
