### ISSUE TITLE
Sections of Undefined in Traveline North West Dataset

### ISSUE THREAD

**Issue by GideonTargomo** [planarnetwork/transxchange2gtfs#25]
Hi, I'm experiencing an issue that seems similar to #12 while working with some Traveline data.

Here is the log from processing all of the Travelline north-west data
```
/usr/local/lib/node_modules/transxchange2gtfs/dist/src/transxchange/TransXChangeJourneyStream.js:32
            const sections = journeyPattern.Sections.reduce((acc, s) => acc.concat(schedule.JourneySections[s]), []);
                                            ^
TypeError: Cannot read property 'Sections' of undefined
    at TransXChangeJourneyStream._transform (/usr/local/lib/node_modules/transxchange2gtfs/dist/src/transxchange/TransXChangeJourneyStream.js:32:45)
    at TransXChangeJourneyStream.Transform._read (_stream_transform.js:189:10)
    at TransXChangeJourneyStream.Readable.read (_stream_readable.js:486:10)
    at flow (_stream_readable.js:994:34)
    at StopTimesStream.pipeOnDrainFunctionResult (_stream_readable.js:798:7)
    at StopTimesStream.emit (events.js:209:13)
    at afterWrite (_stream_writable.js:495:12)
    at onwrite (_stream_writable.js:485:7)
    at StopTimesStream.afterTransform (_stream_transform.js:96:3)
    at StopTimesStream._transform (/usr/local/lib/node_modules/transxchange2gtfs/dist/src/gtfs/GTFSFileStream.js:21:9)
```
After some investigation I found the problem file to be `NW_05_LILT_726_1_B.xml`. 

Here is the full log from just processing the problem file:
```
Processing NW_05_LILT_726_1_B.xml
(node:18750) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Sections' of undefined
    at TransXChangeJourneyStream._transform (/home/gideon/.nvm/versions/node/v14.7.0/lib/node_modules/transxchange2gtfs/dist/src/transxchange/TransXChangeJourneyStream.js:32:45)
    at TransXChangeJourneyStream.Transform._read (_stream_transform.js:205:10)
    at TransXChangeJourneyStream.Transform._write (_stream_transform.js:193:12)
    at writeOrBuffer (_stream_writable.js:352:12)
    at TransXChangeJourneyStream.Writable.write (_stream_writable.js:303:10)
    at TransXChangeStream.ondata (_stream_readable.js:713:22)
    at TransXChangeStream.emit (events.js:326:22)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at TransXChangeStream.Readable.push (_stream_readable.js:218:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18750) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18750) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

From what I can tell this is an issue with the data. The vehicle journeys reference 4 journey plans (JP1-4) but there are only 2 journey plans listed in the XML. While I could try to just remove the missing file I use this data as part of a mostly automated pipeline. I was wondering, would it be possible to add an option to skip files that fail to be processed (with maybe a warning in the log output as to which files failed)?

I have also contacted the data provider but it would be nice to have a workaround for this in the future (especially as it seems that there have been problems with the dataset in the past).

**Comment by linusnorton** [comment]
Agreed. Can you get me a copy of the file and I will work on some better error handling

**Comment by linusnorton** [comment]
I've published a fix in the new version. I didn't have a file to test with though so please test it.

**Comment by GideonTargomo** [comment]
Test locally and it works for me. Here is the file I was having issues with for future reference. Had to zip it as GitHub doesn't let me attach XMLs apparently. Sorry for the delay I wasn't expecting such a quick response. Thanks a lot.
[NW_05_LILT_726_1_B.xml.zip](https://github.com/planarnetwork/transxchange2gtfs/files/5186958/NW_05_LILT_726_1_B.xml.zip)

**Comment by GideonTargomo** [comment]
Hi @linusnorton, Just wanted to check because you said you had published but the latest version of this on https://www.npmjs.com/package/transxchange2gtfs is still 1.6.0 which is the version I get when I install via ´npm install -g´

**Comment by linusnorton** [comment]
Sorry you're right, it didn't get published. It is now.

**Comment by GideonTargomo** [comment]
Thanks
