### ISSUE TITLE
stop: links[0].From.StopPointRef

### ISSUE THREAD

**Issue by timhowgego** [planarnetwork/transxchange2gtfs#33]
Apologies for all the work I'm generating. This error turns up a lot in the current Traveline Yorkshire data. It is not repeatable for individual XMLs, and likewise extracting troublesome XMLs from the parent zip simply causes failure at a different point in the sequence, sometimes on a file that had been processed successfully before that extraction. Ergo it looks like some variable is hanging in the memory from XML to XML, with the potential to confuse the processing of a later XML.

stop: links[0].From.StopPointRef,
                               ^
TypeError: Cannot read property 'From' of undefined
    at TransXChangeJourneyStream.getStopTimes (...\transxchange2gtfs\dist\src\transxchange\TransXChangeJourneyStream.js:120:32)
    at TransXChangeJourneyStream._transform (...\transxchange2gtfs\dist\src\transxchange\TransXChangeJourneyStream.js:40:36)
    at TransXChangeJourneyStream.Transform._read (internal/streams/transform.js:205:10)
    at TransXChangeJourneyStream.Readable.read (internal/streams/readable.js:481:10)
    at flow (internal/streams/readable.js:992:34)
    at StopTimesStream.pipeOnDrainFunctionResult (internal/streams/readable.js:816:7)
    at StopTimesStream.emit (events.js:315:20)
    at afterWrite (internal/streams/writable.js:461:12)
    at onwrite (internal/streams/writable.js:446:7)
    at StopTimesStream.afterTransform (internal/streams/transform.js:103:3)

**Comment by linusnorton** [comment]
`29_REL_2_2021-01-27-01-08_Live_.xml` is missing JourneyPatternSectionRefs JPS_YNGO029-19. I assume it's a data error. I'll see if can be handled more gracefully

**Comment by linusnorton** [comment]
@timhowgego I've published a fix as 1.7.2 - let me know if you have any further issues
