### ISSUE TITLE
Error converting Traveline with latest version

### ISSUE THREAD

**Issue by tafflin** [planarnetwork/transxchange2gtfs#42]
Hi @linusnorton,
In the latest version of txc converter I have a problem converting some of the zip files with txc traveline data. 
The process of conversion is stopped and no GTFS is generated.
I receive this log for some of the files:
```
Processing WM_FG_FSMR_144A_1.xml
(node:7914) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at TransXChangeStream.getOperatingProfile (/usr/lib/node_modules/transxchange2gtfs/dist/src/transxchange/TransXChangeStream.js:170:136)
    at TransXChangeStream.getServices (/usr/lib/node_modules/transxchange2gtfs/dist/src/transxchange/TransXChangeStream.js:110:24)
    at Array.reduce (<anonymous>)
    at TransXChangeStream._transform (/usr/lib/node_modules/transxchange2gtfs/dist/src/transxchange/TransXChangeStream.js:27:49)
    at TransXChangeStream.Transform._read (internal/streams/transform.js:205:10)
    at TransXChangeStream.Transform._write (internal/streams/transform.js:193:12)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at TransXChangeStream.Writable.write (internal/streams/writable.js:303:10)
    at XMLStream.ondata (internal/streams/readable.js:726:22)
    at XMLStream.emit (events.js:400:28)
```
Attached one of the files with such error.
[WM_FG_FSMR_144A_1.zip](https://github.com/planarnetwork/transxchange2gtfs/files/7201639/WM_FG_FSMR_144A_1.zip)

**Comment by tafflin** [comment]
@linusnorton thanks. The convertion is working well
