### ISSUE TITLE
New issue .xml conversion TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by tafflin** [planarnetwork/transxchange2gtfs#44]
In the new version 1.8.7 I found a new error in one of the files.
```
Processing ASDC_652a_l_1_20140831_-_1f294471-f07b-4b8c-950d-68f30aee0eb6.xml
(node:16090) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at TransXChangeStream._transform (/usr/lib/node_modules/transxchange2gtfs/dist/src/transxchange/TransXChangeStream.js:34:37)
    at TransXChangeStream.Transform._read (internal/streams/transform.js:205:10)
    at TransXChangeStream.Transform._write (internal/streams/transform.js:193:12)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at TransXChangeStream.Writable.write (internal/streams/writable.js:303:10)
    at XMLStream.ondata (internal/streams/readable.js:726:22)
    at XMLStream.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at XMLStream.Readable.push (internal/streams/readable.js:204:10)
```

[ASDC_652a_l_1_20140831_-_1f294471-f07b-4b8c-950d-68f30aee0eb6.zip](https://github.com/planarnetwork/transxchange2gtfs/files/7252760/ASDC_652a_l_1_20140831_-_1f294471-f07b-4b8c-950d-68f30aee0eb6.zip)

**Comment by linusnorton** [comment]
@tafflin please try version 1.8.8
