### ISSUE TITLE
Error while conveting .zip files in parallel

### ISSUE THREAD

**Issue by tafflin** [planarnetwork/transxchange2gtfs#50]
Hi @linusnorton ,
We are trying to optimize the conversion time to process Traveline more quickly. To do so I wanted to convert .zip archives in parallel but I get the error while converting:
```
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: file data stream has unexpected number of bytes
    at ByteCounter.<anonymous> (/usr/lib/node_modules/transxchange2gtfs/node_modules/yazl/index.js:160:99)
    at ByteCounter.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ZipFile instance at:
    at ByteCounter.<anonymous> (/usr/lib/node_modules/transxchange2gtfs/node_modules/yazl/index.js:160:85)
    at ByteCounter.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Looks like the converter uses the same tmp/transxchange2gtfs/ folder for storing the temporary gtfs files.

Is there a way to process the data in parallel or use more threads to increase the performance?

**Comment by linusnorton** [comment]
@tafflin I've added the PID to the tmp folder name so you should be able to run it in parallel

**Comment by tafflin** [comment]
Thanks for a quick fix. With time there will be more and more temp folders each with a new name.
Is it also possible to automatically clean the temporary folders after the conversion was successfull?

**Comment by linusnorton** [comment]
try the latest version

**Comment by tafflin** [comment]
Works fine!
