### ISSUE TITLE
could not zip files

### ISSUE THREAD

**Issue by alexdawn** [planarnetwork/transxchange2gtfs#6]
Is there an option not to zip up the resulting gtfs or use a different program?

```
'zip' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:272:12)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'zip -j C:Usersadawnprojectstest_gtfs.zip /tmp/transxchange2gtfs/*.txt',
  stdout: '',
  stderr: '\'zip\' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n' }
```

**Comment by linusnorton** [comment]
I'm sorry but Windows is not supported at this time
